sudo: false
language: node_js
node_js:
  - stable
cache: node_modules
branches:
  only:
    - dev # build dev branch only
script:
  - hexo g # generate static files
after_script:
  - cd ./public
  - git init
  - git config user.name "yefour"
  - git config user.email "1811128205@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force "https://${GH_TOKEN}@github.com/yefour/yefour.github.io.git" master:master
